### ISSUE TITLE
New format

### ISSUE THREAD

**Issue by likevvii** [ludennis/SPPP#11]
This was directly copied and pasted:

<Time, track number, MIDI channel, type, key, value>

Ok. I'm using enum{} C keyword to set numbers, but it is the same as write:
evt_note_off = 0; 
evt_note_on = 1;
evt_aftertouch = 2;
evt_ctrl_change = 3;
evt_prog_change = 4;
evt_chan_keypress = 5;
evt_pitch_bend = 6;
evt_track_end = 7;
evt_track_start = 8;
I want pedal to be sent as ctrl_change with key = 64. This is the same as in MIDI standard

**Comment by ludennis** [comment]
pushed with new format into `master` branch. closing.
